---
- hosts: all
  become: true
  vars:
  tasks:
  
  - name: Create a user with a variable
    hosts: your_target_host
    become: yes #This allows
 
     new_username: your_username_variable
 
     - name: Ensure the user exists
       user:
         name: ramos
         state: present

  - name: install python and pip
    package:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes
  
  - name: use latest pip as default pip in Ubuntu
    command: "ln -sf /usr/bin/python3 /usr/bin/python"
    when: ansible_distribution == 'Ubuntu'

  - name: use latest pip as default pip in CentOS
    command: "ln -sf /usr/bin/python2.7 /usr/bin/python"
    when: ansible_distribution == 'CentOS'

  - name: use latest python as default python in Ubuntu
    command: "ln -sf /usr/bin/python3 /usr/bin/python"
    when: ansible_distribution == 'Ubuntu'

  - name: use latest python as default python in CentOS
    command: "ln -sf /usr/bin/python2.7 /usr/bin/python"
    when: ansible_distribution == 'CentOS' 

  - name: install javeopenjdk Ubuntu
    apt:
      name: openjdk-11-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: install javeopenjdk CentOS
    dnf:
      name: java-11-openjdk-devel  
      state: latest
      update_cache: yes
    when: ansible_distribution == 'CentOS'




